name: Proofreading BL Manuscript Contents
description: Track the results of proofreading the Digital Wright Catalogue
title: "{SHELFMARK} | {URI}"
labels: ["proofreading", "data-edits", "ms-contents"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this proofreading report! Please make sure the name of this issue includes the manuscript's shelfmark and URL.
        The form will guide you through the process of submitting revision requests based on your proofreading.
  - type: markdown
    attributes:
      value: "## Manuscript Contents"
  - type: textarea
    id: ms-contents-desc
    attributes:
      label: Problems with Manuscript Contents
      description: Describe any errors or problems with the Manuscript Contents section. Please describe the problem and paste in a portion of the relevant text.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Additions"
  - type: textarea
    id: additions-desc
    attributes:
      label: Problems with Additions
      description: Describe any errors or problems with the Additions section. Please describe the problem and paste in a portion of the relevant text.
  - type: markdown
    attributes:
      value: "## Missing Content"
  - type: textarea
    id: missing-content-desc
    attributes:
      label: Missing Content
      description: Please describe any missing text here and give the page number (and item, if applicable) in the PDF. If the missing text is in English, please transcribe it from the PDF. 
  - type: markdown
    attributes:
      value: "## Additional Notes"
  - type: textarea
    id: general-notes
    attributes:
      label: General Notes
      description: Provide here any additional notes from proofreading that do not fall into the above categories.
  - type: markdown
    attributes:
      value: |
        Thank you for your help proofreading these manuscript description records!


